### ISSUE TITLE
Permission denied error while starting container with version 1.17.0

### ISSUE THREAD

**Issue by bscx** [tobiasehlert/teslamateapi#273]
I just pulled the latest docker image and after rebuilding and starting it (`docker compose up -d`), this error would show:

`Error response from daemon: OCI runtime create failed: container_linux.go:377: starting container process caused: chdir to cwd ("/root") set in config.json failed: permission denied: unknown`

Can this be related to https://github.com/tobiasehlert/teslamateapi/pull/266?

Please let me know how I can support!

Thanks for your great work!

**Comment by tobiasehlert** [comment]
thanks for reporting @bscx, I'll check into this :)

**Comment by tobiasehlert** [comment]
@bscx, I do not encounter that problem as you describe.. could you please share your docker compose configuration?\
Makes troubleshooting a bit easier :)

Also, are you mounting some configuration into the container for the `COMMANDS_ALLOWLIST` environment variable?\
I don't do that in my setups I'm running, which is my thought right now.

Straight away I would say #266 should not be related, but lets figure it out :)

**Comment by bscx** [comment]
Thanks for looking into this so quickly.

Is the `teslamateapi`section of my docker-compose.yml sufficient?

```
  teslamateapi:
    image: tobiasehlert/teslamateapi:latest
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=XXX
      - DATABASE_USER=teslamate
      - DATABASE_PASS=XXX
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Europe/Berlin
      - API_TOKEN=XXX
      - ENABLE_COMMANDS=false
    ports:
      - 8080:8080
```

I'm executing `docker compose`as non-root user which is in the `docker`group.

Since I'm not too familiar with docker, is the mentioned config.json part of the teslamateapi container or part of my docker configuration?
